---

- name: Automate lab env for terraform
  gather_facts: true
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/packages.yaml

    #- name: Print all available facts.
    # debug:
    #   var: ansible_facts

    - name: Fail when not 22.04
      fail:
        msg: Wrong OS version.
      when: ansible_facts['lsb']['release'] != "22.04"
